---
title: "ps4"
output: html_document
date: "2024-06-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rio)
library(data.table)
library(tidyverse)
library(sf)
library(rvest)
library(ggplot2)
library(viridis)

```
# 1. Extraer la información de internet (50%)

# 1.1 Obtener las URL
url <- "https://eduard-martinez.github.io/pset-4.html"
webpage <- read_html(url)
url_full <- webpage %>% html_nodes("a") %>% html_attr("href") %>% na.omit() %>% unique()

# 1.2 Filtrar URL
url_subset <- url_full[grepl("propiedad", url_full)]
url_subset

# 1.3 Extraer las tablas de los HTML
lista_tablas <- lapply(url_subset, function(link) {
  page <- read_html(link)
  table <- page %>% html_table(fill = TRUE) %>% .[[1]]
  return(table)
})

# 1.4 Preparar información
db_house <- rbindlist(lista_tablas, fill = TRUE)


```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
